spring:
  datasource:
    username: jsok
    password: 123456

    url: jdbc:mysql://localhost:3306/mybatis?severTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
